version: "1.1"

services:
  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: teachease-app

    ports:
      - "3000:3000"
    volumes:
      - ../app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ../app/template.env
